# Generated by Django 2.2.1 on 2019-05-09 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='p_image',
            new_name='property_image',
        ),
        migrations.AddField(
            model_name='properties',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Properties.Addresses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Properties.Details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
