# Generated by Django 2.2.1 on 2019-05-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='secret_entrence',
            new_name='secret_entrance',
        ),
    ]
