# Generated by Django 2.2.1 on 2019-05-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0002_auto_20190515_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
