# Generated by Django 2.2.1 on 2019-05-17 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', models.CharField(max_length=16)),
                ('cc_month', models.CharField(max_length=2)),
                ('cc_year', models.CharField(max_length=2)),
                ('cc_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.CreditCard')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Properties.Properties')),
            ],
        ),
    ]
