# Generated by Django 2.2.1 on 2019-05-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_creditcard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='credit_card',
        ),
    ]
