# Generated by Django 2.2.1 on 2019-05-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_remove_transactions_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
