# Generated by Django 2.2.1 on 2019-05-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_auto_20190516_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cc_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cc_expiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cc_number',
            field=models.IntegerField(),
        ),
    ]
