# Generated by Django 2.2.1 on 2019-05-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0004_auto_20190517_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cc_number',
            field=models.CharField(max_length=16),
        ),
    ]
