# Generated by Django 2.2.1 on 2019-05-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0004_auto_20190517_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cc_number',
            field=models.CharField(max_length=19),
        ),
    ]
