# Generated by Django 2.2.1 on 2019-05-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0005_auto_20190517_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cc_code',
            field=models.CharField(max_length=3),
        ),
    ]
