# Generated by Django 2.2.1 on 2019-05-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0006_auto_20190517_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cc_expiry',
            field=models.DateTimeField(),
        ),
    ]
