# Generated by Django 2.2.1 on 2019-05-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0008_auto_20190517_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='cc_expiry',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='cc_month',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='cc_year',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
