# Generated by Django 2.2.1 on 2019-05-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, blank=True, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=999, blank=True)),
                ('tags', models.CharField(max_length=999, blank=True)),
                ('size', models.CharField(max_length=255, blank=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('search', models.CharField(max_length=255, blank=True, null=True))
            ],
        ),
    ]
