# Generated by Django 2.2.1 on 2019-05-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
                ('type', models.CharField(max_length=999)),
                ('tags', models.CharField(max_length=999)),
                ('size', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('rooms', models.IntegerField()),
            ],
        ),
    ]
