# Generated by Django 2.2.1 on 2019-05-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='property',
        ),
    ]
