# Generated by Django 2.2.1 on 2019-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ssn',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
